### ISSUE TITLE
Display a notice if visitor (hunter or curator) is not in the correct network

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/bounties#131]
- Display a notice if visitor (hunter or curator) is not in the correct network
- **Hide** all of the buttons in the page
- Refer to #66 

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=12140%3A239348)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/183562216-2d8b2c9e-e010-432f-aff3-7be8d361f7ba.png">

**Comment by 2nthony** [comment]
implement in common ui
