### ISSUE TITLE
As a bounty curator, I want to edit a imported bounty info

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/bounties#139]
I found I need to change the bounty description and logo of my imported bounty.

**Comment by Popoulosss** [comment]
Insert a 'more' icon to the content, refer to paid qa

For bounty, curator can
- Replace logo
- Edit title
- Edit description

For child bounty, curator can
- Edit title
- Change tags, if selected
- Edit description

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=12173%3A49589)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/183869235-920bb6e7-09c3-48ec-8948-c183ec038762.png">
