### ISSUE TITLE
Add submission panel to child bounty detail page

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/bounties#178]
![image](https://user-images.githubusercontent.com/6297057/184794084-6f67e141-13e7-429b-95f0-cea9bbe4eff9.png)

**Comment by 2nthony** [comment]
test github inline code css: `bounty -> curator(OpenSquare) -> child bounties -> developers bounty -> curator(OpenSquare) -> child bounties -> developers bounty -> curator(OpenSquare) -> child bounties -> developers `
