### ISSUE TITLE
Improve Mobile layout of Child Bounty application list and submission list

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/bounties#188]
- [x] Application description is too long to display
![image](https://user-images.githubusercontent.com/6297057/185834024-f2f8edf6-8d5c-4f7c-ae8a-fd1e47d70054.png)

- [x] Fix submission mobile layout 
![image](https://user-images.githubusercontent.com/6297057/185834053-2551756c-a8ce-4f0b-8698-78da89210b7e.png)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=12418%3A62196)

Preview
Applicants
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/185853464-3e05f95d-e17c-42f7-88d7-1279a20c612a.png">

Submission
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/185853487-9a5750b8-0562-4ed3-8946-892f000cdb2b.png">

**Comment by hyifeng** [comment]
- [ ] Fix mobile layout of canceled application
![image](https://user-images.githubusercontent.com/6297057/186045113-f481169e-35bb-4841-a2ce-1891d67e9a88.png)

**Comment by hyifeng** [comment]
- [ ]  Refreshing under Mobile mode result to the incorrect layout (Applicants list and Child bounties list)
