### ISSUE TITLE
Improve child bounty list mobile layout

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/bounties#189]
![image](https://user-images.githubusercontent.com/6297057/185834404-e1fb8e24-9619-4dfe-9695-e379fb79c522.png)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=12418%3A63243)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/185869830-489d2a12-f828-4e8e-bc48-c844101e1b32.png">
