### ISSUE TITLE
Improve layout of longer breadcrumb title

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/bounties#200]
![image](https://user-images.githubusercontent.com/6297057/186066003-dd2b4636-0d30-4eee-8c12-13066a19d081.png)

**Comment by 2nthony** [comment]
![origin_img_v2_c9012efa-2180-4174-99e2-d6884f4403bg](https://user-images.githubusercontent.com/19513289/186088035-0fda8c9f-20d1-48be-8f47-6115a7360809.jpg)
