### ISSUE TITLE
"Mark all as read" button on notification page should have a loading status

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/bounties#249]
1. Click
2. Show loading
3. Recover the button when loading end

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=13008%3A55834&viewport=-3447%2C-7517%2C0.48)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/198926771-e7d512bc-eb84-4539-ac26-0371935232d4.png">

**Comment by Popoulosss** [comment]
- [ ] Implement to voting notification
