### ISSUE TITLE
Show error when import bounty without description/title

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/bounties#255]
![TEuZHnr5bS](https://user-images.githubusercontent.com/2264908/202612704-50c6892f-ced5-4ae3-83fb-4785f5c5c64b.jpg)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=9338%3A46753&viewport=-1824%2C-6308%2C0.78&t=ErwverszrZ4LeGUZ-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/204182043-b8769505-6653-4c97-adfd-c60162bf2d03.png">
