### ISSUE TITLE
Don't wrap identity, should use shorten name instead

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/bounties#28]
![image](https://user-images.githubusercontent.com/6297057/179125869-c7aab744-85e4-4c4b-840b-d01ad3affc29.png)

![image](https://user-images.githubusercontent.com/6297057/179125904-a7602909-e3cd-4353-9463-16285ff4546a.png)

Use shorten name as we did in others system:

![image](https://user-images.githubusercontent.com/6297057/179126434-8083488a-12c9-42b4-a27f-0c1f3fb1ed8c.png)

**Comment by 2nthony** [comment]
use common ui IdentityUser
