### ISSUE TITLE
Implement empty bounties list

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/bounties#41]
Need UI design for case of no bounties exists

- [x] Design (@Popoulosss )
- [x] Implement

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=11462%3A48060)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/179198873-e5a5c5a0-3a10-4245-a125-dfd852816877.png">
