### ISSUE TITLE
Show a notice for bounty import

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/bounties#66]
Show a notice area which user can close. This notice won't appear for 2 weeks if closed. In this area, there are warnings:
- You are currently on [kusama|polkadot] network
- Switch to other network if you want to import bounties on it
- Only bounty curators can import bounties

**Comment by Popoulosss** [comment]
- Implement notive card to bounty and child bounty import page

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=11596%3A47944)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/180169606-de02f2b9-8f2c-4d15-bc9e-8c28fbc8cda8.png">
